import { AppLayout } from "@/app/components/AppLayout";
import { RadixTheme } from "@/app/components/RadixTheme";
import { ReactQueryContainer } from "@/app/components/ReactQueryContainer";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryContainer>
          <RadixTheme>
            <AppLayout>{children}</AppLayout>
          </RadixTheme>
        </ReactQueryContainer>
      </body>
    </html>
  );
}
